version: 2
updates:
  # Maintain pnpm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "pnpm"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
          - "typescript-eslint"
          - "@typescript-eslint/*"
      pnpm-frontend-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
