[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fairshare-cli"
version = "0.1.0"
description = "Ein einfaches Python-Tool zum fairen Aufteilen von Kosten."
authors = [
    { name = "Simon", email = "simon@example.com" }
]
dependencies = [
    "PyYAML>=6.0.1",
]
requires-python = ">=3.8"

[project.scripts]
fairshare = "run:main"
